# Uncomment the next line to define a global platform for your project
platform :ios, ’10.0’

target 'IMDBsearch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IMDBsearch
 pod 'SwiftyJSON'

  target 'IMDBsearchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IMDBsearchUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
